# 애플리케이션처럼 앱 프로젝트 CRD는 태그 지정과 같이 관련 있는 애플리케이션을
# 논리적으로 그룹화시켜줄 수 있다. 실무에서는 애플리케이션과 유틸리티 서비스가 분리된다. 
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
  sourceRepos:
  # 매니페스트가 모든 깃 리포지터리에서 배포되도록 허용
  - '*'
  # 애플리케이션이 동일한 클러스터의 guestbook 네임스페이스에만 배포되도록 허용
  destinations:
  - namespace: guestbook
    server: https://kubernetes.default.svc
  # 네임스페이스를 제외하고 모든 클러스터 범위에서 리소스 생성 거부
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace